version: "3"
services:
  gamma:
    image: orbsnetwork/gamma:experimental
    logging:
      driver: "none"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      LOCAL_IP: gamma
    depends_on:
      - gamma
    command: sh -c "sleep 5 && go test ./go/testing/... -v && go test ./go/context/... -v"
