version: 2
jobs:
  tests:
    docker:
      - image: circleci/golang:1.12.6
      - image: orbsnetwork/gamma:experimental
    steps:
      - checkout
      - run: ./test.sh

workflows:
  version: 2
  build:
    jobs:
      - tests