version: 2
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./docker-test.sh

workflows:
  version: 2
  build:
    jobs:
      - tests