version: 2
jobs:
  tests:
    docker:
      - image: circleci/golang:1.11.4
    resource_class: large
    working_directory: /go/src/github.com/orbs-network/orbs-contract-sdk
    steps:
      - setup_remote_docker
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
      - run: sudo apt-get install -y nodejs
      - run: sudo npm install -g truffle
      - run: curl -L https://github.com/orbs-network/gamma-cli/releases/download/v0.6.7/gammacli-linux-x86-64-v0.6.7.tar.gz -o gammacli.tgz && tar zxvf gammacli.tgz && sudo mv _bin/gamma-cli /usr/bin/
      - run: go test ./go/... -v -failfast

workflows:
  version: 2
  build:
    jobs:
      - tests